/**
 * Códigos de erro estáveis e independentes de idioma, retornados em toda
 * resposta de erro da API (`ErrorDto.code`). O cliente usa este valor para
 * localizar a mensagem no idioma do usuário — nunca faça parsing do texto
 * de `message`, que é apenas para debug/log.
 */
export enum ErrorCode {
  // Genéricos / infraestrutura
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  EMAIL_DELIVERY_FAILED = 'EMAIL_DELIVERY_FAILED',

  // Autenticação / credenciais
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNVERIFIED_EMAIL = 'UNVERIFIED_EMAIL',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  PASSWORD_NOT_PROVIDED = 'PASSWORD_NOT_PROVIDED',
  FIREBASE_TOKEN_NOT_PROVIDED = 'FIREBASE_TOKEN_NOT_PROVIDED',
  INVALID_FIREBASE_TOKEN = 'INVALID_FIREBASE_TOKEN',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',

  // Tokens / sessão
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_REVOKED = 'SESSION_REVOKED',

  // Autorização
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  MEMBERSHIP_INVALID = 'MEMBERSHIP_INVALID',
  PROFILE_INVALID = 'PROFILE_INVALID',
  ACCOUNT_ACCESS_DENIED = 'ACCOUNT_ACCESS_DENIED',
  USER_BLOCKED = 'USER_BLOCKED',

  // Usuários / contas
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_NOT_FOUND_IN_ACCOUNT = 'USER_NOT_FOUND_IN_ACCOUNT',
  USER_NOT_MEMBER_OF_ACCOUNT = 'USER_NOT_MEMBER_OF_ACCOUNT',
  USER_ALREADY_IN_ACCOUNT = 'USER_ALREADY_IN_ACCOUNT',
  INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD',
  CANNOT_DELETE_OWNER = 'CANNOT_DELETE_OWNER',
  CANNOT_BLOCK_OWNER = 'CANNOT_BLOCK_OWNER',

  // Verificação de e-mail / redefinição de senha
  INVALID_VERIFICATION_CODE = 'INVALID_VERIFICATION_CODE',
  VERIFICATION_CODE_EXPIRED = 'VERIFICATION_CODE_EXPIRED',
  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED = 'RESET_TOKEN_EXPIRED',

  // FAQ
  FAQ_NOT_FOUND = 'FAQ_NOT_FOUND',
}
