/**
 * Códigos de mensagem de sucesso, paralelos a `ErrorCode`. Resolvidos via
 * i18n (`I18nService`) pelo `TransformInterceptor` a partir do
 * `@SuccessMessage(code)` anexado ao handler — nunca escritos como string
 * solta em Controllers ou Services.
 */
export enum SuccessMessageCode {
  /** Usado quando o handler não anexa um código específico via `@SuccessMessage()`. */
  OPERATION_SUCCESS = 'OPERATION_SUCCESS',

  // Auth
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  LOGOUT_ALL_SUCCESS = 'LOGOUT_ALL_SUCCESS',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  ME_RETRIEVED = 'ME_RETRIEVED',
  ACCOUNT_SWITCHED = 'ACCOUNT_SWITCHED',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  VERIFICATION_RESENT = 'VERIFICATION_RESENT',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',
  SESSIONS_RETRIEVED = 'SESSIONS_RETRIEVED',
  SESSION_REVOKED = 'SESSION_REVOKED',

  // Users
  PROFILE_RETRIEVED = 'PROFILE_RETRIEVED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  AVATAR_UPDATED = 'AVATAR_UPDATED',
  AVATAR_REMOVED = 'AVATAR_REMOVED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PREFERENCES_UPDATED = 'PREFERENCES_UPDATED',
  DATA_RETRIEVED = 'DATA_RETRIEVED',
  USER_INVITED = 'USER_INVITED',
  USER_UPDATED = 'USER_UPDATED',
  USER_STATUS_UPDATED = 'USER_STATUS_UPDATED',

  // FAQ
  FAQ_CREATED = 'FAQ_CREATED',
  FAQ_UPDATED = 'FAQ_UPDATED',
  FAQ_DELETED = 'FAQ_DELETED',
  FAQ_FEEDBACK_REGISTERED = 'FAQ_FEEDBACK_REGISTERED',
}
